- name: Desplegar WordPress y MariaDB en AKS usando imágenes del ACR
  hosts: localhost
  connection: local
  collections:
    - kubernetes.core
  tasks:
    - name: Cargar todos los manifiestos desde el archivo combinado
      set_fact:
        k8s_resources: "{{ lookup('file', 'wordpress-mysql.yml') | from_yaml_all }}"

    - name: Aplicar manifiestos en AKS
      kubernetes.core.k8s:
        state: present
        definition: "{{ item }}"
      loop: "{{ k8s_resources }}"