---
- name: Desplegar aplicaci贸n en AKS con almacenamiento persistente
  hosts: kubernetes
  tasks:
    - name: Crear un archivo de configuraci贸n para la aplicaci贸n
      copy:
        dest: "/tmp/app_deployment.yml"
        content: |
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: app-pvc
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi

          ---
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: my-app
            template:
              metadata:
                labels:
                  app: my-app
              spec:
                containers:
                  - name: my-app
                    image: nginx
                    ports:
                      - containerPort: 80
                    volumeMounts:
                      - mountPath: "/usr/share/nginx/html"
                        name: storage
                volumes:
                  - name: storage
                    persistentVolumeClaim:
                      claimName: app-pvc

          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: my-app-service
          spec:
            selector:
              app: my-app
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer

    - name: Aplicar la configuraci贸n en AKS
      command: kubectl apply -f /tmp/app_deployment.yml
