---
- name: Instalar y configurar servidor web Nginx desde ACR en Podman
  hosts: webserver
  become: true
  collections:
    - containers.podman
    - community.general
  vars_files:
    - secrets.yml
  tasks:
    - name: Autenticarse en ACR desde Podman
      podman_login:
        registry: cp2acrckd0cf.azurecr.io
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Instalar Podman
      apt:
        name: podman
        state: present
        update_cache: yes

    - name: Ejecutar contenedor Nginx desde ACR en Podman
      podman_container:
        name: nginx-server
        image: cp2acrckd0cf.azurecr.io/nginx:latest
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "80:80"
